#!/bin/sh /etc/rc.common

START=18

start() {
	MODE=`/sbin/uci get wireless.@wifi-iface[0].mode`
	SSID=`/sbin/uci get wireless.@wifi-iface[0].ssid`

	if [ "$MODE" == "ap" -a "$SSID" == "Arduino" ]
	then
		SSID_SUFFIX=`hexdump -v -e '1/1 "%.2x"' -s $((0x120)) -n 2 /dev/mtd6`
		SSID="SeeeduinoCloud-A$SSID_SUFFIX"
		/sbin/uci "set" "wireless.@wifi-iface[0].ssid=$SSID"
		/sbin/uci commit wireless
		logger -t rename "WiFi renamed $SSID"
	fi
}

